const data = [
  {
    id: 1,
    name: 'Jeff Bezos',
    networth: 177,
    age: 57,
    country: 'United States',
    source: 'Amazon',
    industry: 'Technology',
  },
  {
    id: 2,
    name: 'Elon Musk',
    networth: 151,
    age: 49,
    country: 'United States',
    source: 'Tesla, SpaceX',
    industry: 'Automotive',
  },
  {
    id: 3,
    name: 'Bernard Arnault & family',
    networth: 150,
    age: 72,
    country: 'France',
    source: 'LVMH',
    industry: 'Fashion & Retail',
  },
  {
    id: 4,
    name: 'Bill Gates',
    networth: 124,
    age: 65,
    country: 'United States',
    source: 'Microsoft',
    industry: 'Technology',
  },
  {
    id: 5,
    name: 'Mark Zuckerberg',
    networth: 97,
    age: 36,
    country: 'United States',
    source: 'Facebook',
    industry: 'Technology',
  },
  {
    id: 6,
    name: 'Warren Buffett',
    networth: 96,
    age: 90,
    country: 'United States',
    source: 'Berkshire Hathaway',
    industry: 'Finance & Investment',
  },
  {
    id: 7,
    name: 'Larry Ellison',
    networth: 93,
    age: 76,
    country: 'United States',
    source: 'Software',
    industry: 'Technology',
  },
  {
    id: 8,
    name: 'Larry Page',
    networth: 91.5,
    age: 48,
    country: 'United States',
    source: 'Google',
    industry: 'Technology',
  },
  {
    id: 9,
    name: 'Sergey Brin',
    networth: 89,
    age: 47,
    country: 'United States',
    source: 'Google',
    industry: 'Technology',
  },
  {
    id: 10,
    name: 'Mukesh Ambani',
    networth: 84.5,
    age: 63,
    country: 'India',
    source: 'diversified',
    industry: 'Diversified',
  },
  {
    id: 11,
    name: 'Amancio Ortega',
    networth: 77,
    age: 85,
    country: 'Spain',
    source: 'Zara',
    industry: 'Fashion & Retail',
  },
  {
    id: 12,
    name: 'Francoise Bettencourt Meyers & family',
    networth: 73.6,
    age: 67,
    country: 'France',
    source: 'L`oreal',
    industry: 'Fashion & Retail',
  },
  {
    id: 13,
    name: 'Zhong Shanshan',
    networth: 68.9,
    age: 66,
    country: 'China',
    source: 'Beverages & Pharmaceuticals',
    industry: 'Food & Beverage',
  },
  {
    id: 14,
    name: 'Steve Ballmer',
    networth: 68.7,
    age: 65,
    country: 'United States',
    source: 'Microsoft',
    industry: 'Technology',
  },
  {
    id: 15,
    name: 'Ma Huateng',
    networth: 65.8,
    age: 49,
    country: 'China',
    source: 'Internet Media',
    industry: 'Technology',
  },
];
